title = "Ferrara Ebraica | MEIS"
defaultContentLanguage = "it"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm", "tag"]

[languages]
  [languages.en]
    languageName = "EN"
    weight = 2
    [languages.en.params]
      description = "Ferrara Ebraica Exhibition at MEIS"
  [languages.it]
    languageName = "IT"
    weight = 1
    [languages.it.params]
      description = "Mostra 'Ferrara Ebraica' presso il MEIS, Museo Nazionale dell'Ebraismo Italiano e della Shoah"

