[build.environment]
  NPM_VERSION = "6.13.4"

[build]
  command = "npm run prebuild && mkdir -p dist && ls && npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm build:preview"
